server:
  port: 8080
# Spring配置
spring:

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      # 配置数据库连接信息
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mall-pms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useUnicode=true&allowPublicKeyRetrieval=true
      username: root
      password: root
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  # 配置日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# MP配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #设置主键自增
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.xiaofei.generator

#设置日志级别
logging:
  level:
    com.xiaofei.product: info


